var user = [{
  "login": "lancegputnam",
  "id": 6868568,
  "avatar_url": "https://avatars.githubusercontent.com/u/6868568?",
  "gravatar_id": "a2859174ff92374fa3db125ecbbd58e8",
  "url": "https://api.github.com/users/lancegputnam",
  "html_url": "https://github.com/lancegputnam",
  "followers_url": "https://api.github.com/users/lancegputnam/followers",
  "following_url": "https://api.github.com/users/lancegputnam/following{/other_user}",
  "gists_url": "https://api.github.com/users/lancegputnam/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/lancegputnam/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/lancegputnam/subscriptions",
  "organizations_url": "https://api.github.com/users/lancegputnam/orgs",
  "repos_url": "https://api.github.com/users/lancegputnam/repos",
  "events_url": "https://api.github.com/users/lancegputnam/events{/privacy}",
  "received_events_url": "https://api.github.com/users/lancegputnam/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Lance Putnam",
  "company": "The Iron Yard",
  "blog": "",
  "location": "Greenville, SC",
  "email": "",
  "hireable": false,
  "bio": null,
  "public_repos": 8,
  "public_gists": 0,
  "followers": 5,
  "following": 5,
  "created_at": "2014-03-06T03:09:45Z",
  "updated_at": "2014-05-14T12:36:43Z"
}];

var repos = [{
      "id": 19725644,
      "name": "day-11-jquery",
      "full_name": "lancegputnam/day-11-jquery",
      "owner": {
      "login": "lancegputnam",
      "id": 6868568,
      "avatar_url": "https://avatars.githubusercontent.com/u/6868568?",
      "gravatar_id": "a2859174ff92374fa3db125ecbbd58e8",
      "url": "https://api.github.com/users/lancegputnam",
      "html_url": "https://github.com/lancegputnam",
      "followers_url": "https://api.github.com/users/lancegputnam/followers",
      "following_url": "https://api.github.com/users/lancegputnam/following{/other_user}",
      "gists_url": "https://api.github.com/users/lancegputnam/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lancegputnam/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lancegputnam/subscriptions",
      "organizations_url": "https://api.github.com/users/lancegputnam/orgs",
      "repos_url": "https://api.github.com/users/lancegputnam/repos",
      "events_url": "https://api.github.com/users/lancegputnam/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lancegputnam/received_events",
      "type": "User",
      "site_admin": false
  },
    "private": false,
    "html_url": "https://github.com/lancegputnam/day-11-jquery",
    "description": "jQuery Examples and Etsy API",
    "fork": false,
    "url": "https://api.github.com/repos/lancegputnam/day-11-jquery",
    "forks_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/forks",
    "keys_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/teams",
    "hooks_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/hooks",
    "issue_events_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/events",
    "assignees_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/tags",
    "blobs_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/languages",
    "stargazers_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/stargazers",
    "contributors_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/contributors",
    "subscribers_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/subscribers",
    "subscription_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/subscription",
    "commits_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/merges",
    "archive_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/downloads",
    "issues_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/labels{/name}",
    "releases_url": "https://api.github.com/repos/lancegputnam/day-11-jquery/releases{/id}",
    "created_at": "2014-05-13T04:19:40Z",
    "updated_at": "2014-05-13T04:22:43Z",
    "pushed_at": "2014-05-13T04:22:43Z",
    "git_url": "git://github.com/lancegputnam/day-11-jquery.git",
    "ssh_url": "git@github.com:lancegputnam/day-11-jquery.git",
    "clone_url": "https://github.com/lancegputnam/day-11-jquery.git",
    "svn_url": "https://github.com/lancegputnam/day-11-jquery",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 19766250,
    "name": "day-12-jquery-examples",
    "full_name": "lancegputnam/day-12-jquery-examples",
    "owner": {
      "login": "lancegputnam",
      "id": 6868568,
      "avatar_url": "https://avatars.githubusercontent.com/u/6868568?",
      "gravatar_id": "a2859174ff92374fa3db125ecbbd58e8",
      "url": "https://api.github.com/users/lancegputnam",
      "html_url": "https://github.com/lancegputnam",
      "followers_url": "https://api.github.com/users/lancegputnam/followers",
      "following_url": "https://api.github.com/users/lancegputnam/following{/other_user}",
      "gists_url": "https://api.github.com/users/lancegputnam/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lancegputnam/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lancegputnam/subscriptions",
      "organizations_url": "https://api.github.com/users/lancegputnam/orgs",
      "repos_url": "https://api.github.com/users/lancegputnam/repos",
      "events_url": "https://api.github.com/users/lancegputnam/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lancegputnam/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lancegputnam/day-12-jquery-examples",
    "description": "Working with Yeoman",
    "fork": false,
    "url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples",
    "forks_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/forks",
    "keys_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/teams",
    "hooks_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/hooks",
    "issue_events_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/events",
    "assignees_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/tags",
    "blobs_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/languages",
    "stargazers_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/stargazers",
    "contributors_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/contributors",
    "subscribers_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/subscribers",
    "subscription_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/subscription",
    "commits_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/merges",
    "archive_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/downloads",
    "issues_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/labels{/name}",
    "releases_url": "https://api.github.com/repos/lancegputnam/day-12-jquery-examples/releases{/id}",
    "created_at": "2014-05-14T04:26:34Z",
    "updated_at": "2014-05-14T12:36:43Z",
    "pushed_at": "2014-05-14T04:27:52Z",
    "git_url": "git://github.com/lancegputnam/day-12-jquery-examples.git",
    "ssh_url": "git@github.com:lancegputnam/day-12-jquery-examples.git",
    "clone_url": "https://github.com/lancegputnam/day-12-jquery-examples.git",
    "svn_url": "https://github.com/lancegputnam/day-12-jquery-examples",
    "homepage": "",
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 19561562,
    "name": "day-eight-js",
    "full_name": "lancegputnam/day-eight-js",
    "owner": {
      "login": "lancegputnam",
      "id": 6868568,
      "avatar_url": "https://avatars.githubusercontent.com/u/6868568?",
      "gravatar_id": "a2859174ff92374fa3db125ecbbd58e8",
      "url": "https://api.github.com/users/lancegputnam",
      "html_url": "https://github.com/lancegputnam",
      "followers_url": "https://api.github.com/users/lancegputnam/followers",
      "following_url": "https://api.github.com/users/lancegputnam/following{/other_user}",
      "gists_url": "https://api.github.com/users/lancegputnam/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lancegputnam/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lancegputnam/subscriptions",
      "organizations_url": "https://api.github.com/users/lancegputnam/orgs",
      "repos_url": "https://api.github.com/users/lancegputnam/repos",
      "events_url": "https://api.github.com/users/lancegputnam/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lancegputnam/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lancegputnam/day-eight-js",
    "description": "JS Examples",
    "fork": false,
    "url": "https://api.github.com/repos/lancegputnam/day-eight-js",
    "forks_url": "https://api.github.com/repos/lancegputnam/day-eight-js/forks",
    "keys_url": "https://api.github.com/repos/lancegputnam/day-eight-js/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lancegputnam/day-eight-js/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lancegputnam/day-eight-js/teams",
    "hooks_url": "https://api.github.com/repos/lancegputnam/day-eight-js/hooks",
    "issue_events_url": "https://api.github.com/repos/lancegputnam/day-eight-js/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lancegputnam/day-eight-js/events",
    "assignees_url": "https://api.github.com/repos/lancegputnam/day-eight-js/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lancegputnam/day-eight-js/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lancegputnam/day-eight-js/tags",
    "blobs_url": "https://api.github.com/repos/lancegputnam/day-eight-js/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lancegputnam/day-eight-js/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lancegputnam/day-eight-js/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lancegputnam/day-eight-js/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lancegputnam/day-eight-js/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lancegputnam/day-eight-js/languages",
    "stargazers_url": "https://api.github.com/repos/lancegputnam/day-eight-js/stargazers",
    "contributors_url": "https://api.github.com/repos/lancegputnam/day-eight-js/contributors",
    "subscribers_url": "https://api.github.com/repos/lancegputnam/day-eight-js/subscribers",
    "subscription_url": "https://api.github.com/repos/lancegputnam/day-eight-js/subscription",
    "commits_url": "https://api.github.com/repos/lancegputnam/day-eight-js/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lancegputnam/day-eight-js/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lancegputnam/day-eight-js/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lancegputnam/day-eight-js/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lancegputnam/day-eight-js/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lancegputnam/day-eight-js/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lancegputnam/day-eight-js/merges",
    "archive_url": "https://api.github.com/repos/lancegputnam/day-eight-js/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lancegputnam/day-eight-js/downloads",
    "issues_url": "https://api.github.com/repos/lancegputnam/day-eight-js/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lancegputnam/day-eight-js/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lancegputnam/day-eight-js/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lancegputnam/day-eight-js/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lancegputnam/day-eight-js/labels{/name}",
    "releases_url": "https://api.github.com/repos/lancegputnam/day-eight-js/releases{/id}",
    "created_at": "2014-05-08T05:23:35Z",
    "updated_at": "2014-05-12T16:49:32Z",
    "pushed_at": "2014-05-12T16:49:30Z",
    "git_url": "git://github.com/lancegputnam/day-eight-js.git",
    "ssh_url": "git@github.com:lancegputnam/day-eight-js.git",
    "clone_url": "https://github.com/lancegputnam/day-eight-js.git",
    "svn_url": "https://github.com/lancegputnam/day-eight-js",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 19442010,
    "name": "day-five-project",
    "full_name": "lancegputnam/day-five-project",
    "owner": {
      "login": "lancegputnam",
      "id": 6868568,
      "avatar_url": "https://avatars.githubusercontent.com/u/6868568?",
      "gravatar_id": "a2859174ff92374fa3db125ecbbd58e8",
      "url": "https://api.github.com/users/lancegputnam",
      "html_url": "https://github.com/lancegputnam",
      "followers_url": "https://api.github.com/users/lancegputnam/followers",
      "following_url": "https://api.github.com/users/lancegputnam/following{/other_user}",
      "gists_url": "https://api.github.com/users/lancegputnam/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lancegputnam/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lancegputnam/subscriptions",
      "organizations_url": "https://api.github.com/users/lancegputnam/orgs",
      "repos_url": "https://api.github.com/users/lancegputnam/repos",
      "events_url": "https://api.github.com/users/lancegputnam/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lancegputnam/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lancegputnam/day-five-project",
    "description": "Project with 30 CSS examples",
    "fork": false,
    "url": "https://api.github.com/repos/lancegputnam/day-five-project",
    "forks_url": "https://api.github.com/repos/lancegputnam/day-five-project/forks",
    "keys_url": "https://api.github.com/repos/lancegputnam/day-five-project/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lancegputnam/day-five-project/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lancegputnam/day-five-project/teams",
    "hooks_url": "https://api.github.com/repos/lancegputnam/day-five-project/hooks",
    "issue_events_url": "https://api.github.com/repos/lancegputnam/day-five-project/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lancegputnam/day-five-project/events",
    "assignees_url": "https://api.github.com/repos/lancegputnam/day-five-project/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lancegputnam/day-five-project/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lancegputnam/day-five-project/tags",
    "blobs_url": "https://api.github.com/repos/lancegputnam/day-five-project/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lancegputnam/day-five-project/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lancegputnam/day-five-project/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lancegputnam/day-five-project/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lancegputnam/day-five-project/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lancegputnam/day-five-project/languages",
    "stargazers_url": "https://api.github.com/repos/lancegputnam/day-five-project/stargazers",
    "contributors_url": "https://api.github.com/repos/lancegputnam/day-five-project/contributors",
    "subscribers_url": "https://api.github.com/repos/lancegputnam/day-five-project/subscribers",
    "subscription_url": "https://api.github.com/repos/lancegputnam/day-five-project/subscription",
    "commits_url": "https://api.github.com/repos/lancegputnam/day-five-project/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lancegputnam/day-five-project/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lancegputnam/day-five-project/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lancegputnam/day-five-project/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lancegputnam/day-five-project/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lancegputnam/day-five-project/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lancegputnam/day-five-project/merges",
    "archive_url": "https://api.github.com/repos/lancegputnam/day-five-project/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lancegputnam/day-five-project/downloads",
    "issues_url": "https://api.github.com/repos/lancegputnam/day-five-project/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lancegputnam/day-five-project/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lancegputnam/day-five-project/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lancegputnam/day-five-project/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lancegputnam/day-five-project/labels{/name}",
    "releases_url": "https://api.github.com/repos/lancegputnam/day-five-project/releases{/id}",
    "created_at": "2014-05-05T02:51:26Z",
    "updated_at": "2014-05-14T12:35:29Z",
    "pushed_at": "2014-05-14T12:35:28Z",
    "git_url": "git://github.com/lancegputnam/day-five-project.git",
    "ssh_url": "git@github.com:lancegputnam/day-five-project.git",
    "clone_url": "https://github.com/lancegputnam/day-five-project.git",
    "svn_url": "https://github.com/lancegputnam/day-five-project",
    "homepage": null,
    "size": 112,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 19652569,
    "name": "day-nine-js",
    "full_name": "lancegputnam/day-nine-js",
    "owner": {
      "login": "lancegputnam",
      "id": 6868568,
      "avatar_url": "https://avatars.githubusercontent.com/u/6868568?",
      "gravatar_id": "a2859174ff92374fa3db125ecbbd58e8",
      "url": "https://api.github.com/users/lancegputnam",
      "html_url": "https://github.com/lancegputnam",
      "followers_url": "https://api.github.com/users/lancegputnam/followers",
      "following_url": "https://api.github.com/users/lancegputnam/following{/other_user}",
      "gists_url": "https://api.github.com/users/lancegputnam/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lancegputnam/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lancegputnam/subscriptions",
      "organizations_url": "https://api.github.com/users/lancegputnam/orgs",
      "repos_url": "https://api.github.com/users/lancegputnam/repos",
      "events_url": "https://api.github.com/users/lancegputnam/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lancegputnam/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lancegputnam/day-nine-js",
    "description": "Javascript Examples with Objects, Arrays, forEach, reduce, map",
    "fork": false,
    "url": "https://api.github.com/repos/lancegputnam/day-nine-js",
    "forks_url": "https://api.github.com/repos/lancegputnam/day-nine-js/forks",
    "keys_url": "https://api.github.com/repos/lancegputnam/day-nine-js/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lancegputnam/day-nine-js/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lancegputnam/day-nine-js/teams",
    "hooks_url": "https://api.github.com/repos/lancegputnam/day-nine-js/hooks",
    "issue_events_url": "https://api.github.com/repos/lancegputnam/day-nine-js/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lancegputnam/day-nine-js/events",
    "assignees_url": "https://api.github.com/repos/lancegputnam/day-nine-js/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lancegputnam/day-nine-js/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lancegputnam/day-nine-js/tags",
    "blobs_url": "https://api.github.com/repos/lancegputnam/day-nine-js/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lancegputnam/day-nine-js/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lancegputnam/day-nine-js/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lancegputnam/day-nine-js/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lancegputnam/day-nine-js/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lancegputnam/day-nine-js/languages",
    "stargazers_url": "https://api.github.com/repos/lancegputnam/day-nine-js/stargazers",
    "contributors_url": "https://api.github.com/repos/lancegputnam/day-nine-js/contributors",
    "subscribers_url": "https://api.github.com/repos/lancegputnam/day-nine-js/subscribers",
    "subscription_url": "https://api.github.com/repos/lancegputnam/day-nine-js/subscription",
    "commits_url": "https://api.github.com/repos/lancegputnam/day-nine-js/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lancegputnam/day-nine-js/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lancegputnam/day-nine-js/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lancegputnam/day-nine-js/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lancegputnam/day-nine-js/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lancegputnam/day-nine-js/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lancegputnam/day-nine-js/merges",
    "archive_url": "https://api.github.com/repos/lancegputnam/day-nine-js/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lancegputnam/day-nine-js/downloads",
    "issues_url": "https://api.github.com/repos/lancegputnam/day-nine-js/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lancegputnam/day-nine-js/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lancegputnam/day-nine-js/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lancegputnam/day-nine-js/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lancegputnam/day-nine-js/labels{/name}",
    "releases_url": "https://api.github.com/repos/lancegputnam/day-nine-js/releases{/id}",
    "created_at": "2014-05-10T21:35:36Z",
    "updated_at": "2014-05-14T12:35:41Z",
    "pushed_at": "2014-05-14T12:35:40Z",
    "git_url": "git://github.com/lancegputnam/day-nine-js.git",
    "ssh_url": "git@github.com:lancegputnam/day-nine-js.git",
    "clone_url": "https://github.com/lancegputnam/day-nine-js.git",
    "svn_url": "https://github.com/lancegputnam/day-nine-js",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "JavaScript",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 19316673,
    "name": "day-one-project",
    "full_name": "lancegputnam/day-one-project",
    "owner": {
      "login": "lancegputnam",
      "id": 6868568,
      "avatar_url": "https://avatars.githubusercontent.com/u/6868568?",
      "gravatar_id": "a2859174ff92374fa3db125ecbbd58e8",
      "url": "https://api.github.com/users/lancegputnam",
      "html_url": "https://github.com/lancegputnam",
      "followers_url": "https://api.github.com/users/lancegputnam/followers",
      "following_url": "https://api.github.com/users/lancegputnam/following{/other_user}",
      "gists_url": "https://api.github.com/users/lancegputnam/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lancegputnam/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lancegputnam/subscriptions",
      "organizations_url": "https://api.github.com/users/lancegputnam/orgs",
      "repos_url": "https://api.github.com/users/lancegputnam/repos",
      "events_url": "https://api.github.com/users/lancegputnam/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lancegputnam/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lancegputnam/day-one-project",
    "description": "Learning how to use Git with Day 1 Homework",
    "fork": false,
    "url": "https://api.github.com/repos/lancegputnam/day-one-project",
    "forks_url": "https://api.github.com/repos/lancegputnam/day-one-project/forks",
    "keys_url": "https://api.github.com/repos/lancegputnam/day-one-project/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lancegputnam/day-one-project/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lancegputnam/day-one-project/teams",
    "hooks_url": "https://api.github.com/repos/lancegputnam/day-one-project/hooks",
    "issue_events_url": "https://api.github.com/repos/lancegputnam/day-one-project/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lancegputnam/day-one-project/events",
    "assignees_url": "https://api.github.com/repos/lancegputnam/day-one-project/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lancegputnam/day-one-project/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lancegputnam/day-one-project/tags",
    "blobs_url": "https://api.github.com/repos/lancegputnam/day-one-project/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lancegputnam/day-one-project/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lancegputnam/day-one-project/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lancegputnam/day-one-project/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lancegputnam/day-one-project/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lancegputnam/day-one-project/languages",
    "stargazers_url": "https://api.github.com/repos/lancegputnam/day-one-project/stargazers",
    "contributors_url": "https://api.github.com/repos/lancegputnam/day-one-project/contributors",
    "subscribers_url": "https://api.github.com/repos/lancegputnam/day-one-project/subscribers",
    "subscription_url": "https://api.github.com/repos/lancegputnam/day-one-project/subscription",
    "commits_url": "https://api.github.com/repos/lancegputnam/day-one-project/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lancegputnam/day-one-project/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lancegputnam/day-one-project/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lancegputnam/day-one-project/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lancegputnam/day-one-project/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lancegputnam/day-one-project/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lancegputnam/day-one-project/merges",
    "archive_url": "https://api.github.com/repos/lancegputnam/day-one-project/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lancegputnam/day-one-project/downloads",
    "issues_url": "https://api.github.com/repos/lancegputnam/day-one-project/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lancegputnam/day-one-project/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lancegputnam/day-one-project/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lancegputnam/day-one-project/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lancegputnam/day-one-project/labels{/name}",
    "releases_url": "https://api.github.com/repos/lancegputnam/day-one-project/releases{/id}",
    "created_at": "2014-04-30T14:40:13Z",
    "updated_at": "2014-05-14T12:36:22Z",
    "pushed_at": "2014-05-14T12:36:21Z",
    "git_url": "git://github.com/lancegputnam/day-one-project.git",
    "ssh_url": "git@github.com:lancegputnam/day-one-project.git",
    "clone_url": "https://github.com/lancegputnam/day-one-project.git",
    "svn_url": "https://github.com/lancegputnam/day-one-project",
    "homepage": null,
    "size": 132,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 19463485,
    "name": "day-six-project",
    "full_name": "lancegputnam/day-six-project",
    "owner": {
      "login": "lancegputnam",
      "id": 6868568,
      "avatar_url": "https://avatars.githubusercontent.com/u/6868568?",
      "gravatar_id": "a2859174ff92374fa3db125ecbbd58e8",
      "url": "https://api.github.com/users/lancegputnam",
      "html_url": "https://github.com/lancegputnam",
      "followers_url": "https://api.github.com/users/lancegputnam/followers",
      "following_url": "https://api.github.com/users/lancegputnam/following{/other_user}",
      "gists_url": "https://api.github.com/users/lancegputnam/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lancegputnam/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lancegputnam/subscriptions",
      "organizations_url": "https://api.github.com/users/lancegputnam/orgs",
      "repos_url": "https://api.github.com/users/lancegputnam/repos",
      "events_url": "https://api.github.com/users/lancegputnam/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lancegputnam/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lancegputnam/day-six-project",
    "description": "30 CSS Examples with Sass",
    "fork": false,
    "url": "https://api.github.com/repos/lancegputnam/day-six-project",
    "forks_url": "https://api.github.com/repos/lancegputnam/day-six-project/forks",
    "keys_url": "https://api.github.com/repos/lancegputnam/day-six-project/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lancegputnam/day-six-project/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lancegputnam/day-six-project/teams",
    "hooks_url": "https://api.github.com/repos/lancegputnam/day-six-project/hooks",
    "issue_events_url": "https://api.github.com/repos/lancegputnam/day-six-project/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lancegputnam/day-six-project/events",
    "assignees_url": "https://api.github.com/repos/lancegputnam/day-six-project/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lancegputnam/day-six-project/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lancegputnam/day-six-project/tags",
    "blobs_url": "https://api.github.com/repos/lancegputnam/day-six-project/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lancegputnam/day-six-project/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lancegputnam/day-six-project/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lancegputnam/day-six-project/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lancegputnam/day-six-project/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lancegputnam/day-six-project/languages",
    "stargazers_url": "https://api.github.com/repos/lancegputnam/day-six-project/stargazers",
    "contributors_url": "https://api.github.com/repos/lancegputnam/day-six-project/contributors",
    "subscribers_url": "https://api.github.com/repos/lancegputnam/day-six-project/subscribers",
    "subscription_url": "https://api.github.com/repos/lancegputnam/day-six-project/subscription",
    "commits_url": "https://api.github.com/repos/lancegputnam/day-six-project/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lancegputnam/day-six-project/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lancegputnam/day-six-project/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lancegputnam/day-six-project/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lancegputnam/day-six-project/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lancegputnam/day-six-project/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lancegputnam/day-six-project/merges",
    "archive_url": "https://api.github.com/repos/lancegputnam/day-six-project/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lancegputnam/day-six-project/downloads",
    "issues_url": "https://api.github.com/repos/lancegputnam/day-six-project/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lancegputnam/day-six-project/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lancegputnam/day-six-project/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lancegputnam/day-six-project/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lancegputnam/day-six-project/labels{/name}",
    "releases_url": "https://api.github.com/repos/lancegputnam/day-six-project/releases{/id}",
    "created_at": "2014-05-05T16:57:03Z",
    "updated_at": "2014-05-14T12:36:12Z",
    "pushed_at": "2014-05-14T12:36:12Z",
    "git_url": "git://github.com/lancegputnam/day-six-project.git",
    "ssh_url": "git@github.com:lancegputnam/day-six-project.git",
    "clone_url": "https://github.com/lancegputnam/day-six-project.git",
    "svn_url": "https://github.com/lancegputnam/day-six-project",
    "homepage": null,
    "size": 7600,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  },
  {
    "id": 19321909,
    "name": "day-two-project",
    "full_name": "lancegputnam/day-two-project",
    "owner": {
      "login": "lancegputnam",
      "id": 6868568,
      "avatar_url": "https://avatars.githubusercontent.com/u/6868568?",
      "gravatar_id": "a2859174ff92374fa3db125ecbbd58e8",
      "url": "https://api.github.com/users/lancegputnam",
      "html_url": "https://github.com/lancegputnam",
      "followers_url": "https://api.github.com/users/lancegputnam/followers",
      "following_url": "https://api.github.com/users/lancegputnam/following{/other_user}",
      "gists_url": "https://api.github.com/users/lancegputnam/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lancegputnam/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lancegputnam/subscriptions",
      "organizations_url": "https://api.github.com/users/lancegputnam/orgs",
      "repos_url": "https://api.github.com/users/lancegputnam/repos",
      "events_url": "https://api.github.com/users/lancegputnam/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lancegputnam/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/lancegputnam/day-two-project",
    "description": "Surf & Paddle Project",
    "fork": false,
    "url": "https://api.github.com/repos/lancegputnam/day-two-project",
    "forks_url": "https://api.github.com/repos/lancegputnam/day-two-project/forks",
    "keys_url": "https://api.github.com/repos/lancegputnam/day-two-project/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/lancegputnam/day-two-project/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/lancegputnam/day-two-project/teams",
    "hooks_url": "https://api.github.com/repos/lancegputnam/day-two-project/hooks",
    "issue_events_url": "https://api.github.com/repos/lancegputnam/day-two-project/issues/events{/number}",
    "events_url": "https://api.github.com/repos/lancegputnam/day-two-project/events",
    "assignees_url": "https://api.github.com/repos/lancegputnam/day-two-project/assignees{/user}",
    "branches_url": "https://api.github.com/repos/lancegputnam/day-two-project/branches{/branch}",
    "tags_url": "https://api.github.com/repos/lancegputnam/day-two-project/tags",
    "blobs_url": "https://api.github.com/repos/lancegputnam/day-two-project/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/lancegputnam/day-two-project/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/lancegputnam/day-two-project/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/lancegputnam/day-two-project/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/lancegputnam/day-two-project/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/lancegputnam/day-two-project/languages",
    "stargazers_url": "https://api.github.com/repos/lancegputnam/day-two-project/stargazers",
    "contributors_url": "https://api.github.com/repos/lancegputnam/day-two-project/contributors",
    "subscribers_url": "https://api.github.com/repos/lancegputnam/day-two-project/subscribers",
    "subscription_url": "https://api.github.com/repos/lancegputnam/day-two-project/subscription",
    "commits_url": "https://api.github.com/repos/lancegputnam/day-two-project/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/lancegputnam/day-two-project/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/lancegputnam/day-two-project/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/lancegputnam/day-two-project/issues/comments/{number}",
    "contents_url": "https://api.github.com/repos/lancegputnam/day-two-project/contents/{+path}",
    "compare_url": "https://api.github.com/repos/lancegputnam/day-two-project/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/lancegputnam/day-two-project/merges",
    "archive_url": "https://api.github.com/repos/lancegputnam/day-two-project/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/lancegputnam/day-two-project/downloads",
    "issues_url": "https://api.github.com/repos/lancegputnam/day-two-project/issues{/number}",
    "pulls_url": "https://api.github.com/repos/lancegputnam/day-two-project/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/lancegputnam/day-two-project/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/lancegputnam/day-two-project/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/lancegputnam/day-two-project/labels{/name}",
    "releases_url": "https://api.github.com/repos/lancegputnam/day-two-project/releases{/id}",
    "created_at": "2014-04-30T17:40:06Z",
    "updated_at": "2014-05-14T12:36:01Z",
    "pushed_at": "2014-05-14T12:36:00Z",
    "git_url": "git://github.com/lancegputnam/day-two-project.git",
    "ssh_url": "git@github.com:lancegputnam/day-two-project.git",
    "clone_url": "https://github.com/lancegputnam/day-two-project.git",
    "svn_url": "https://github.com/lancegputnam/day-two-project",
    "homepage": null,
    "size": 136,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  }
];


var getNameTemplate = _.template($('.repositories').text());

$.getJSON('https://api.github.com/users/lancegputnam/repos').done(function(repos){
    renderRepos(repos);
});

////////////// This function renders the main content on the page //////////////////////////
function renderRepos (repos){
    repos.forEach(function(repo){

        var rendered = getNameTemplate(repo);

        $('.mainbar').append(rendered);
    });
}

////////// This renders the sidebar content on the page ///////////////
var getProfileTemplate = _.template($('.profile').text());

  user.forEach(function(user){

    var rendered = getProfileTemplate(user);

    $('.sidebar').append(rendered);
  })

























